const {getLetters, getPosition} =  require('./data/getInfo');
const newPosition = Object.entries(getPosition);
const newLetters = Object.entries(getLetters);

const {getUrl, orderUrl,link} = require('./index');

const characterPositions = [
    { char: '1', position: [ 34 ] },
    { char: '2', position: [ 65 ] },
    { char: '5', position: [ 66, 78 ] },
    { char: '7', position: [ 67, 76 ] },
    { char: '8', position: [ 81 ] },
    { char: 'I', position: [ 37 ] },
    { char: 'H', position: [ 73 ] },
    { char: 't', position: [ 1, 2 ] },
    { char: 'G', position: [ 46 ] },
    { char: 'u', position: [ 63 ] },
    { char: 'k', position: [ 45 ] },
    { char: 'P', position: [ 49 ] },
    { char: 'e', position: [ 18, 32, 59, 93 ] },
    { char: 'p', position: [ 3, 38, 43 ] },
    { char: 'm', position: [ 22, 27, 98 ] },
    { char: 'i', position: [ 58, 92 ] },
    { char: 'v', position: [ 74, 91 ] },
    { char: 's', position: [ 4, 11, 28, 69 ] },
    { char: 'L', position: [ 40 ] },
    { char: 'w', position: [ 60, 94 ] },
    { char: 'f', position: [ 24, 47, 72, 95 ] },
    { char: 'z', position: [ 75 ] },
    { char: 'F', position: [ 35, 86 ] },
    { char: 'l', position: [ 17 ] },
    { char: 'R', position: [ 61 ] },
    { char: 'D', position: [ 53 ] },
    { char: 'A', position: [ 36 ] },
    { char: 'r', position: [ 26, 48, 97 ] },
    { char: 'T', position: [ 80, 84 ] },
    { char: 'Q', position: [ 39 ] },
    { char: '/', position: [6,  7, 23, 29,31, 33, 90]},
    { char: 'y', position: [ 77, 88 ] },
    { char: 'W', position: [ 44, 68 ] },
    { char: 'h', position: [ 0, 50 ] },
    { char: 'j', position: [ 56, 70 ] },
    { char: 'x', position: [ 64, 71 ] },
    { char: 'O', position: [ 83 ] },
    { char: 'o', position: [ 9, 14, 15, 21, 25, 96 ] },
    { char: 'C', position: [ 62, 82 ] },
    { char: 'g', position: [ 13, 16, 89 ] },
    { char: 'S', position: [ 41, 57 ] },
    { char: '.', position: [ 12, 19 ] },
    { char: 'n', position: [ 52, 87 ] },
    { char: ':', position: [ 5 ] },
    { char: 'q', position: [ 51, 55, 79 ] },
    { char: 'c', position: [ 10, 20, 42 ] },
    { char: 'a', position: [ 54 ] },
    { char: 'Y', position: [ 85 ] },
    { char: 'd', position: [ 8, 30 ] }
  ]

const orderPositions = [
    { char: 'h', position: 0 },
    { char: 't', position: 1 },
    { char: 't', position: 2 },
    { char: 'p', position: 3 },
    { char: 's', position: 4 },
    { char: ':', position: 5 },
    { char: '/', position: 6 },
    { char: '/', position: 7 },
    { char: 'd', position: 8 },
    { char: 'o', position: 9 },
    { char: 'c', position: 10 },
    { char: 's', position: 11 },
    { char: '.', position: 12 },
    { char: 'g', position: 13 },
    { char: 'o', position: 14 },
    { char: 'o', position: 15 },
    { char: 'g', position: 16 },
    { char: 'l', position: 17 },
    { char: 'e', position: 18 },
    { char: '.', position: 19 },
    { char: 'c', position: 20 },
    { char: 'o', position: 21 },
    { char: 'm', position: 22 },
    { char: '/', position: 23 },
    { char: 'f', position: 24 },
    { char: 'o', position: 25 },
    { char: 'r', position: 26 },
    { char: 'm', position: 27 },
    { char: 's', position: 28 },
    { char: '/', position: 29 },
    { char: 'd', position: 30 },
    { char: '/', position: 31 },
    { char: 'e', position: 32 },
    { char: '/', position: 33 },
    { char: '1', position: 34 },
    { char: 'F', position: 35 },
    { char: 'A', position: 36 },
    { char: 'I', position: 37 },
    { char: 'p', position: 38 },
    { char: 'Q', position: 39 },
    { char: 'L', position: 40 },
    { char: 'S', position: 41 },
    { char: 'c', position: 42 },
    { char: 'p', position: 43 },
    { char: 'W', position: 44 },
    { char: 'k', position: 45 },
    { char: 'G', position: 46 },
    { char: 'f', position: 47 },
    { char: 'r', position: 48 },
    { char: 'P', position: 49 },
    { char: 'h', position: 50 },
    { char: 'q', position: 51 },
    { char: 'n', position: 52 },
    { char: 'D', position: 53 },
    { char: 'a', position: 54 },
    { char: 'q', position: 55 },
    { char: 'j', position: 56 },
    { char: 'S', position: 57 },
    { char: 'i', position: 58 },
    { char: 'e', position: 59 },
    { char: 'w', position: 60 },
    { char: 'R', position: 61 },
    { char: 'C', position: 62 },
    { char: 'u', position: 63 },
    { char: 'x', position: 64 },
    { char: '2', position: 65 },
    { char: '5', position: 66 },
    { char: '7', position: 67 },
    { char: 'W', position: 68 },
    { char: 's', position: 69 },
    { char: 'j', position: 70 },
    { char: 'x', position: 71 },
    { char: 'f', position: 72 },
    { char: 'H', position: 73 },
    { char: 'v', position: 74 },
    { char: 'z', position: 75 },
    { char: '7', position: 76 },
    { char: 'y', position: 77 },
    { char: '5', position: 78 },
    { char: 'q', position: 79 },
    { char: 'T', position: 80 },
    { char: '8', position: 81 },
    { char: 'C', position: 82 },
    { char: 'O', position: 83 },
    { char: 'T', position: 84 },
    { char: 'Y', position: 85 },
    { char: 'F', position: 86 },
    { char: 'n', position: 87 },
    { char: 'y', position: 88 },
    { char: 'g', position: 89 },
    { char: '/', position: 90 },
    { char: 'v', position: 91 },
    { char: 'i', position: 92 },
    { char: 'e', position: 93 },
    { char: 'w', position: 94 },
    { char: 'f', position: 95 },
    { char: 'o', position: 96 },
    { char: 'r', position: 97 },
    { char: 'm', position: 98 }
  ]

describe('Las funciones getUrl, orderUrl, link en conjunto deben retornar el link', () => {

    test("getUrl debe retornar la asociación de los caracteres y sus posiciones",()=>{

        expect( getUrl(newLetters,newPosition) ).toEqual(characterPositions)
    });

    test("orderUrl debe tomar el array que retorna getUrl y ordenar las posiciones con sus caracteres",()=>{

        expect( orderUrl(getUrl(newLetters, newPosition)) ).toEqual(orderPositions)
    });

    test("link debe tomar el array que devuelve orderUrl y retornar el link al formulario",()=>{

        expect( link(orderUrl(getUrl(newLetters, newPosition))) ).toBe('https://docs.google.com/forms/d/e/1FAIpQLScpWkGfrPhqnDaqjSiewRCux257WsjxfHvz7y5qT8COTYFnyg/viewform')
    });
});
